
#define USE_USER_VECTOR
#define USE_USER_VALUE_LIMIT
#define USE_USER_FRAME
#define USE_USER_MATRIX
#define USE_USER_RAW_TO_ENGINEERING
#define USE_USER_EULAR_TO_MATRIX
#define USE_USER_QUATERNION_TO_MATRIX
#define USE_USER_SPHERE_TO_RECTANGULAR
#define USE_USER_RAND
#define USE_USER_RANDOM
#define USE_USER_TIME
#define USE_USER_QUATERNION
#define USE_USER_EULAR_TO_QUATERNION
#define USE_USER_SMOOTH